/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gix.change_c_pointer

class App {

    public var address: Long = 0

    val greeting: String
        get() {
            return "Hello World!"
        }

    // native interface

    fun setAddressPtr(addr: Long) {
        address = addr
    }

    external fun createMyData()

    external fun doubleGrade(addressPointer: Long)

    companion object {
        init {
            System.loadLibrary("change_c_pointer")
        }
    }
}
